spring.application.name=Simple-LLM-Api

spring.ai.google.genai.api-key=${ANTHROPIC_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.5-flash-lite

logging.level.org.springframework.ai.chat.client.advisor=DEBUG

#DB config
spring.datasource.url=jdbc:mysql://localhost:3308/dev
spring.datasource.username=sovon9
spring.datasource.password=password

spring.jpa.show-sql=true

# to create the table always
spring.ai.chat.memory.repository.jdbc.initialize-schema=always